#!/bin/bash
# Setup script for new GitHub repository

echo "==================================================================="
echo "Git Repository Setup Instructions"
echo "==================================================================="
echo ""
echo "Your repository has been prepared with:"
echo "  - DNABERT2 code and documentation"
echo "  - LAMAR implementation and evaluation"
echo "  - Data analysis scripts (no large data files)"
echo "  - Comprehensive .gitignore"
echo "  - README.md and module documentation"
echo ""
echo "Total files committed: 61"
echo "Lines of code added: ~12,000"
echo ""
echo "==================================================================="
echo "STEP 1: Create a new GitHub repository"
echo "==================================================================="
echo ""
echo "1. Go to: https://github.com/new"
echo "2. Repository name: (e.g., 'dna-language-models-rbp')"
echo "3. Description: 'DNA Language Models for RBP Binding Prediction'"
echo "4. Choose: Public or Private"
echo "5. DO NOT initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "==================================================================="
echo "STEP 2: Add the new remote and push"
echo "==================================================================="
echo ""
echo "After creating the repository on GitHub, run these commands:"
echo ""
echo "# Replace YOUR_USERNAME and YOUR_REPO with your actual values:"
echo "git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git"
echo ""
echo "# Or if you use SSH:"
echo "# git remote add origin git@github.com:YOUR_USERNAME/YOUR_REPO.git"
echo ""
echo "# Push to the new repository:"
echo "git push -u origin master"
echo ""
echo "==================================================================="
echo "STEP 3: (Optional) Remove old remote"
echo "==================================================================="
echo ""
echo "After successfully pushing to the new remote:"
echo "git remote remove old-origin"
echo ""
echo "==================================================================="
echo "Current repository status:"
echo "==================================================================="
echo ""

git log --oneline -5
echo ""
echo "Old remote (will be removed later):"
git remote -v

echo ""
echo "==================================================================="
echo "What's included:"
echo "==================================================================="
echo ""
echo "✓ DNABERT2 training and evaluation scripts"
echo "✓ LAMAR model implementation (ESM-2 based)"
echo "✓ Data analysis scripts (GC/AU, k-mer analysis)"
echo "✓ Comprehensive documentation files"
echo "✓ Environment configuration files (.yml)"
echo "✓ SLURM job generation scripts"
echo ""
echo "What's excluded (via .gitignore):"
echo "==================================================================="
echo ""
echo "✗ Large data files (.fa, .fasta, .h5, .bed)"
echo "✗ Model checkpoints (.bin, .safetensors, .pth)"
echo "✗ Training outputs and logs"
echo "✗ Preprocessed datasets (.arrow files)"
echo "✗ Python cache and temporary files"
echo ""
echo "==================================================================="
echo "Repository size (tracked files only):"
git ls-files | xargs du -ch 2>/dev/null | tail -1
echo "==================================================================="
echo ""
